cc_library(
	name = "command_line",
	srcs = ["CommandLine.cpp"],
	hdrs = ["CommandLine.h"  ],
	deps = [
		"//abort:abort",
		"//types:types",
		"//util:util"
	],
	visibility = [
		"//perft:__pkg__",
		"//bench:__pkg__",
	],
)
