cc_binary(
	name  = "bench",
	srcs  = ["bench.cpp"],
	copts = ["-O4"],
	deps  = [
		"//CommandLine:command_line",
		"//src:chess",
	],
)

cc_binary(
    name  = "bench4",
    srcs  = ["bench4.cpp"],
    copts = ["-O4"],
    deps  = [
        "//CommandLine:command_line",
        "//src:chess",
    ],
)
